// Validation for the Travel Spend cloud API. Pure (no DB) so it can be unit
// tested. Reuses the name-based participant + receipt validators shared with the
// share payload, since a cloud trip persists exactly the client Receipt shape.

import { ValidationError, validateParticipantsJson, ValidatedParticipant } from "@/lib/validation";
import { validateSharedReceipts, SharedReceipt } from "@/lib/shared-summary";

const MAX_TRIP_NAME = 200;
const MAX_BUDGET = 1_000_000_000_000; // 1 trillion rupiah ceiling (abuse guard)

export interface ValidatedTravelTrip {
  name: string;
  budget?: number;
  participants: ValidatedParticipant[];
  receipts: SharedReceipt[];
}

/**
 * Validate a full Travel trip body (create or guest→cloud sync): name, optional
 * budget, name-based participants, and 0+ receipts referencing those
 * participants. Receipts may be empty (a brand-new trip has none yet).
 */
export function validateTravelTripInput(body: unknown): ValidatedTravelTrip {
  if (!body || typeof body !== "object") {
    throw new ValidationError("body", "must be an object");
  }
  const b = body as Record<string, unknown>;

  const rawName = typeof b.name === "string" ? b.name.trim() : "";
  const name = (rawName || "My Trip").slice(0, MAX_TRIP_NAME);

  const budget = validateBudget(b.budget);

  const participants = validateParticipantsJson(b.participants, "participants") ?? [];
  const participantIds = new Set(participants.map((p) => p.id));
  const receipts = validateSharedReceipts(b.receipts ?? [], participantIds);

  return { name, budget, participants, receipts };
}

/** Optional positive money budget; returns undefined for missing/≤0/invalid. */
export function validateBudget(value: unknown): number | undefined {
  if (value == null || value === "") return undefined;
  const n = typeof value === "number" ? value : parseFloat(String(value));
  if (!Number.isFinite(n) || n <= 0) return undefined;
  if (n > MAX_BUDGET) throw new ValidationError("budget", "exceeds maximum");
  return n;
}

/**
 * Validate a single receipt payload (per-receipt endpoints) against the trip's
 * participant ids. Reuses the array validator for one receipt.
 */
export function validateTripReceiptPayload(
  payload: unknown,
  participantIds: Set<string>
): SharedReceipt {
  return validateSharedReceipts([payload], participantIds, { requireAtLeastOne: true })[0];
}

const MAX_PAYMENT_NOTE = 200;
const MAX_PAYMENT_AMOUNT = 1_000_000_000; // 1 billion rupiah ceiling

const MAX_PAYMENT_SOURCE = 200;

export interface ValidatedTripPayment {
  from: string;
  to: string;
  amount: number;
  note?: string;
  source?: string;
}

/**
 * Validate a settle-up payment body: `from`/`to` must be distinct participants
 * of the trip and `amount` a positive, bounded number. `note` + `source` are
 * optional (`source` marks payments generated by a receipt-share checkbox).
 */
export function validateTripPaymentInput(
  body: unknown,
  participantIds: Set<string>
): ValidatedTripPayment {
  if (!body || typeof body !== "object") {
    throw new ValidationError("body", "must be an object");
  }
  const b = body as Record<string, unknown>;

  const from = typeof b.from === "string" ? b.from : "";
  const to = typeof b.to === "string" ? b.to : "";
  if (!participantIds.has(from)) throw new ValidationError("from", "must be a participant");
  if (!participantIds.has(to)) throw new ValidationError("to", "must be a participant");
  if (from === to) throw new ValidationError("to", "must differ from the payer");

  const amount = typeof b.amount === "number" ? b.amount : parseFloat(String(b.amount ?? ""));
  if (!Number.isFinite(amount) || amount <= 0) {
    throw new ValidationError("amount", "must be a positive number");
  }
  if (amount > MAX_PAYMENT_AMOUNT) throw new ValidationError("amount", "exceeds maximum amount");

  let note: string | undefined;
  if (b.note != null && b.note !== "") {
    if (typeof b.note !== "string") throw new ValidationError("note", "must be a string");
    note = b.note.trim().slice(0, MAX_PAYMENT_NOTE) || undefined;
  }

  let source: string | undefined;
  if (b.source != null && b.source !== "") {
    if (typeof b.source !== "string") throw new ValidationError("source", "must be a string");
    source = b.source.slice(0, MAX_PAYMENT_SOURCE);
  }

  return { from, to, amount, ...(note ? { note } : {}), ...(source ? { source } : {}) };
}
